const FETCH_GIFS_REQUEST = 'GIPHY/SEARCH/FETCH_GIFS/REQUEST';
const FETCH_GIFS_SUCCESS = 'GIPHY/SEARCH/FETCH_GIFS/SUCCESS';
const FETCH_GIFS_FAILURE = 'GIPHY/SEARCH/FETCH_GIFS/FAILURE';

const FETCH_GIFS_APPEND_SUCCESS = 'GIPHY/SEARCH/FETCH_GIFS_APPEND/SUCCESS';

const FETCH_GIFS_LOADING = 'GIPHY/SEARCH/FETCH_GIFS/LOADING';

const CLEAR_SEARCH_TERM_SUCCESS = 'GIPHY/SEARCH/CLEAR_SEARCH_TERM/SUCCESS';

export {
  FETCH_GIFS_REQUEST,
  FETCH_GIFS_SUCCESS,
  FETCH_GIFS_LOADING,
  CLEAR_SEARCH_TERM_SUCCESS,
  FETCH_GIFS_APPEND_SUCCESS,
  FETCH_GIFS_FAILURE,
};
