const FETCH_GIFS_REQUEST = 'GIPHY/SEARCH/FETCH_GIFS/REQUEST';
const FETCH_GIFS_SUCCESS = 'GIPHY/SEARCH/FETCH_GIFS/SUCCESS';

const FETCH_GIFS_LOADING = 'GIPHY/SEARCH/FETCH_GIFS/LOADING';

export {
  FETCH_GIFS_REQUEST,
  FETCH_GIFS_SUCCESS,
  FETCH_GIFS_LOADING,
};
